--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);


ALTER TABLE public.app_user OWNER TO panosdim;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: panosdim
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.movie (
    id bigint NOT NULL,
    movie_id integer,
    poster character varying(255),
    rating integer,
    title character varying(255),
    user_id character varying(255),
    watched boolean
);


ALTER TABLE public.movie OWNER TO panosdim;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: panosdim
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie_providers; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.movie_providers (
    movie_id bigint NOT NULL,
    logo_path character varying(255),
    provider_name character varying(255)
);


ALTER TABLE public.movie_providers OWNER TO panosdim;

--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: panosdim
--

COPY public.app_user (id, email, first_name, last_name, password) FROM stdin;
1	panosdim@gmail.com	Panagiotis	Dimopoulos	$2a$10$14bdb30a9532c3ca582b3uc4wgQIWf3ol788aCWrb4ne8JlhpfvIG
\.


--
-- Data for Name: movie; Type: TABLE DATA; Schema: public; Owner: panosdim
--

COPY public.movie (id, movie_id, poster, rating, title, user_id, watched) FROM stdin;
11	1100988	/5SyBozBOc2PGH6QIIlMDpfOCB5b.jpg	0	28 Years Later	panosdim@gmail.com	f
26	1234821	/8BZ6oGDE336qFshFC44WxZtosBX.jpg	0	Jurassic World Rebirth	panosdim@gmail.com	f
28	696506	/lrCcovGRcuv8Z1v3ae1ZH5Ird05.jpg	0	Mickey 17	panosdim@gmail.com	f
1	533535	/uxBHXaoOvAwy4NpPpP7nNx2rXYQ.jpg	3	Deadpool & Wolverine	panosdim@gmail.com	t
2	519182	/aun2IpLDx2E08hYj8xnAEUEFLlo.jpg	4	Despicable Me 4	panosdim@gmail.com	t
3	558449	/f54mzACTFdiAxnQ30BK4GjrKzyn.jpg	4	Gladiator II	panosdim@gmail.com	t
5	945961	/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg	3	Alien: Romulus	panosdim@gmail.com	t
6	1022789	/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg	4	Inside Out 2	panosdim@gmail.com	t
7	1011985	/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg	4	Kung Fu Panda 4	panosdim@gmail.com	t
8	653346	/gKkl37BQuKTanygYQG1pyYgLVgf.jpg	4	Kingdom of the Planet of the Apes	panosdim@gmail.com	t
9	573435	/oGythE98MYleE6mZlGs5oBGkux1.jpg	3	Bad Boys: Ride or Die	panosdim@gmail.com	t
10	762441	/hU42CRk14JuPEdqZG3AWmagiPAP.jpg	2	A Quiet Place: Day One	panosdim@gmail.com	t
12	1184918	/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg	5	The Wild Robot	panosdim@gmail.com	t
13	912649	/8mRrl8lc7TrbdA1PFzUhQ0nFZ7R.jpg	3	Venom: The Last Dance	panosdim@gmail.com	t
14	845781	/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg	3	Red One	panosdim@gmail.com	t
15	299536	/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg	5	Avengers: Infinity War	panosdim@gmail.com	t
16	1726	/78lPtwv72eTNqFW9COBYI0dWDJa.jpg	5	Iron Man	panosdim@gmail.com	t
17	807	/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg	5	Se7en	panosdim@gmail.com	t
18	877817	/vOX1Zng472PC2KnS0B9nRfM8aaZ.jpg	3	Wolfs	panosdim@gmail.com	t
19	299534	/or06FN3Dka5tukK1e9sl16pB3iy.jpg	5	Avengers: Endgame	panosdim@gmail.com	t
20	976734	/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg	3	Canary Black	panosdim@gmail.com	t
22	1241982	/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg	4	Moana 2	panosdim@gmail.com	t
23	539972	/i47IUSsN126K11JUzqQIOi1Mg1M.jpg	3	Kraven the Hunter	panosdim@gmail.com	t
24	866398	/A7EByudX0eOzlkQ2FIbogzyazm2.jpg	3	The Beekeeper	panosdim@gmail.com	t
29	950396	/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg	4	The Gorge	panosdim@gmail.com	t
30	307081	/kSQ49Fi3NVTqGGXILmxV2T2pdkG.jpg	4	Southpaw	panosdim@gmail.com	t
37	541671	/mKp4euM5Cv3m2U1Vmby3OGwcD5y.jpg	\N	Ballerina	panosdim@gmail.com	\N
38	1011477	/c90Lt7OQGsOmhv6x4JoFdoHzw5l.jpg	\N	Karate Kid: Legends	panosdim@gmail.com	\N
42	1376434	/2XDQa6EmFHSA37j1t0w88vpWqj9.jpg	3	Predator: Killer of Killers	panosdim@gmail.com	t
4	822119	/jmobYdUXrbj1g5QFWjeomOk2Noz.jpg	4	Captain America: Brave New World	panosdim@gmail.com	t
50	950387	/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg	3	A Minecraft Movie	panosdim@gmail.com	t
51	604079	/wobVTa99eW0ht6c1rNNzLkazPtR.jpg	\N	The Long Walk	panosdim@gmail.com	\N
55	1087891	/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg	4	The Amateur	panosdim@gmail.com	t
27	986056	/jrlCcyFJek3BWnZhpU6MHtTMoDK.jpg	4	Thunderbolts*	panosdim@gmail.com	t
56	425274	/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg	\N	Now You See Me: Now You Don't	panosdim@gmail.com	\N
57	1054867	/rA3d4NDeTUVIVCfQtnxGzZ672N8.jpg	\N	One Battle After Another	panosdim@gmail.com	\N
62	83533	/lE9KpVwgeWHMwgwkNaeH5nEFh20.jpg	\N	Avatar: Fire and Ash	panosdim@gmail.com	\N
58	157336	/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg	4	Interstellar	panosdim@gmail.com	t
60	926393	/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg	4	The Equalizer 3	panosdim@gmail.com	t
59	460465	/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg	3	Mortal Kombat	panosdim@gmail.com	t
35	911430	/vqBmyAj0Xm9LnS1xe1MSlMAJyHq.jpg	5	F1 The Movie	panosdim@gmail.com	t
31	1233413	/yqsCU5XOP2mkbFamzAqbqntmfav.jpg	4	Sinners	panosdim@gmail.com	t
39	547016	/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg	3	The Old Guard	panosdim@gmail.com	t
52	1078605	/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg	3	Weapons	panosdim@gmail.com	t
61	1363123	/semFxuYx6HcrkZzslgAkBqfJvZk.jpg	4	The Family Plan 2	panosdim@gmail.com	t
41	1061474	/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg	2	Superman	panosdim@gmail.com	t
40	846422	/qjVMsjV7UmSpi1aHA9Wtl1v8cxr.jpg	3	The Old Guard 2	panosdim@gmail.com	t
54	1062722	/2ixPMFWyKtQ9C4ROo9xA12ci2yU.jpg	4	Frankenstein	panosdim@gmail.com	t
21	575265	/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg	5	Mission: Impossible - The Final Reckoning	panosdim@gmail.com	t
36	617126	/x26MtUlwtWD26d0G0FXcppxCJio.jpg	4	The Fantastic Four: First Steps	panosdim@gmail.com	t
32	870028	/4rxr2grcBfxwH4penSxndcPwyDp.jpg	4	The Accountant 2	panosdim@gmail.com	t
64	687163	/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg	\N	Project Hail Mary	panosdim@gmail.com	\N
65	1226863	/dQFwdkCpfc5UOdQigYKQm06VJS4.jpg	\N	The Super Mario Galaxy Movie	panosdim@gmail.com	\N
68	1265609	/rFhKkXhk7ClU03jQ5rHIApJDwev.jpg	\N	War Machine	panosdim@gmail.com	\N
66	1168190	/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg	3	The Wrecking Crew	panosdim@gmail.com	t
69	1236153	/pyok1kZJCfyuFapYXzHcy7BLlQa.jpg	\N	Mercy	panosdim@gmail.com	\N
43	1242898	/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg	4	Predator: Badlands	panosdim@gmail.com	t
70	1170608	/b4wekkUaxExzOeGe7hKXzhnyXHt.jpg	\N	Dune: Part Three	panosdim@gmail.com	\N
71	969681	/b53rTpY2kG3XAuGQzHjBRo7jf0Z.jpg	\N	Spider-Man: Brand New Day	panosdim@gmail.com	\N
53	533533	/lyq8uQzxWTCIxWEKuxyQPrbVu40.jpg	4	TRON: Ares	panosdim@gmail.com	t
\.


--
-- Data for Name: movie_providers; Type: TABLE DATA; Schema: public; Owner: panosdim
--

COPY public.movie_providers (movie_id, logo_path, provider_name) FROM stdin;
11	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV
38	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV
28	/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg	Google Play Movies
28	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV Store
57	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV Store
26	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV Store
68	/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg	Netflix
69	/SPnB1qiCkYfirS2it3hZORwGVn.jpg	Apple TV Store
\.


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: panosdim
--

SELECT pg_catalog.setval('public.app_user_id_seq', 1, true);


--
-- Name: movie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: panosdim
--

SELECT pg_catalog.setval('public.movie_id_seq', 71, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: panosdim
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: panosdim
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- Name: movie_providers fkluutfy9g56y6klgbt04opeoam; Type: FK CONSTRAINT; Schema: public; Owner: panosdim
--

ALTER TABLE ONLY public.movie_providers
    ADD CONSTRAINT fkluutfy9g56y6klgbt04opeoam FOREIGN KEY (movie_id) REFERENCES public.movie(id);


--
-- PostgreSQL database dump complete
--

