--
-- Initialization script — runs only on first container start (empty volume).
-- Creates the role if it does not already exist, then restores the schema and data.
--

-- Create the application role if missing (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'panosdim') THEN
    CREATE ROLE panosdim WITH LOGIN PASSWORD 'Test1!';
  END IF;
END
$$;

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);

ALTER TABLE public.app_user OWNER TO panosdim;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: panosdim
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: movie; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.movie (
    id bigint NOT NULL,
    movie_id integer,
    poster character varying(255),
    rating integer,
    title character varying(255),
    user_id character varying(255),
    watched boolean
);

ALTER TABLE public.movie OWNER TO panosdim;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: panosdim
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: movie_providers; Type: TABLE; Schema: public; Owner: panosdim
--

CREATE TABLE public.movie_providers (
    movie_id bigint NOT NULL,
    logo_path character varying(255),
    provider_name character varying(255)
);

ALTER TABLE public.movie_providers OWNER TO panosdim;

--
-- Data for Name: app_user
--

COPY public.app_user (id, email, first_name, last_name, password) FROM stdin;
1	panosdim@gmail.com	Panagiotis	Dimopoulos	$2a$10$14bdb30a9532c3ca582b3uc4wgQIWf3ol788aCWrb4ne8JlhpfvIG
\.

--
-- Data for Name: movie
--

COPY public.movie (id, movie_id, poster, rating, title, user_id, watched) FROM stdin;
11	1100988	/5SyBozBOc2PGH6QIIlMDpfOCB5b.jpg	0	28 Years Later	panosdim@gmail.com	f
21	575265	/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg	0	Mission: Impossible - The Final Reckoning	panosdim@gmail.com	f
25	1233575	/yCVJ8joYTzf9tCby9o9H7zhEVG8.jpg	0	Black Bag	panosdim@gmail.com	f
26	1234821	/8BZ6oGDE336qFshFC44WxZtosBX.jpg	0	Jurassic World Rebirth	panosdim@gmail.com	f
28	696506	/lrCcovGRcuv8Z1v3ae1ZH5Ird05.jpg	0	Mickey 17	panosdim@gmail.com	f
31	1233413	/yqsCU5XOP2mkbFamzAqbqntmfav.jpg	0	Sinners	panosdim@gmail.com	f
32	870028	/4rxr2grcBfxwH4penSxndcPwyDp.jpg	0	The Accountant 2	panosdim@gmail.com	f
1	533535	/uxBHXaoOvAwy4NpPpP7nNx2rXYQ.jpg	3	Deadpool & Wolverine	panosdim@gmail.com	t
2	519182	/aun2IpLDx2E08hYj8xnAEUEFLlo.jpg	4	Despicable Me 4	panosdim@gmail.com	t
3	558449	/f54mzACTFdiAxnQ30BK4GjrKzyn.jpg	4	Gladiator II	panosdim@gmail.com	t
5	945961	/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg	3	Alien: Romulus	panosdim@gmail.com	t
6	1022789	/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg	4	Inside Out 2	panosdim@gmail.com	t
7	1011985	/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg	4	Kung Fu Panda 4	panosdim@gmail.com	t
8	653346	/gKkl37BQuKTanygYQG1pyYgLVgf.jpg	4	Kingdom of the Planet of the Apes	panosdim@gmail.com	t
9	573435	/oGythE98MYleE6mZlGs5oBGkux1.jpg	3	Bad Boys: Ride or Die	panosdim@gmail.com	t
10	762441	/hU42CRk14JuPEdqZG3AWmagiPAP.jpg	2	A Quiet Place: Day One	panosdim@gmail.com	t
12	1184918	/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg	5	The Wild Robot	panosdim@gmail.com	t
13	912649	/8mRrl8lc7TrbdA1PFzUhQ0nFZ7R.jpg	3	Venom: The Last Dance	panosdim@gmail.com	t
14	845781	/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg	3	Red One	panosdim@gmail.com	t
15	299536	/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg	5	Avengers: Infinity War	panosdim@gmail.com	t
16	1726	/78lPtwv72eTNqFW9COBYI0dWDJa.jpg	5	Iron Man	panosdim@gmail.com	t
17	807	/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg	5	Se7en	panosdim@gmail.com	t
18	877817	/vOX1Zng472PC2KnS0B9nRfM8aaZ.jpg	3	Wolfs	panosdim@gmail.com	t
19	299534	/or06FN3Dka5tukK1e9sl16pB3iy.jpg	5	Avengers: Endgame	panosdim@gmail.com	t
20	976734	/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg	3	Canary Black	panosdim@gmail.com	t
22	1241982	/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg	4	Moana 2	panosdim@gmail.com	t
23	539972	/i47IUSsN126K11JUzqQIOi1Mg1M.jpg	3	Kraven the Hunter	panosdim@gmail.com	t
24	866398	/A7EByudX0eOzlkQ2FIbogzyazm2.jpg	3	The Beekeeper	panosdim@gmail.com	t
29	950396	/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg	4	The Gorge	panosdim@gmail.com	t
30	307081	/kSQ49Fi3NVTqGGXILmxV2T2pdkG.jpg	4	Southpaw	panosdim@gmail.com	t
35	911430	/vqBmyAj0Xm9LnS1xe1MSlMAJyHq.jpg	\N	F1 The Movie	panosdim@gmail.com	\N
36	617126	/x26MtUlwtWD26d0G0FXcppxCJio.jpg	\N	The Fantastic Four: First Steps	panosdim@gmail.com	\N
37	541671	/mKp4euM5Cv3m2U1Vmby3OGwcD5y.jpg	\N	Ballerina	panosdim@gmail.com	\N
38	1011477	/c90Lt7OQGsOmhv6x4JoFdoHzw5l.jpg	\N	Karate Kid: Legends	panosdim@gmail.com	\N
39	547016	/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg	\N	The Old Guard	panosdim@gmail.com	\N
40	846422	/qjVMsjV7UmSpi1aHA9Wtl1v8cxr.jpg	\N	The Old Guard 2	panosdim@gmail.com	\N
41	1061474	/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg	\N	Superman	panosdim@gmail.com	\N
43	1242898	/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg	\N	Predator: Badlands	panosdim@gmail.com	\N
42	1376434	/2XDQa6EmFHSA37j1t0w88vpWqj9.jpg	3	Predator: Killer of Killers	panosdim@gmail.com	t
4	822119	/jmobYdUXrbj1g5QFWjeomOk2Noz.jpg	4	Captain America: Brave New World	panosdim@gmail.com	t
50	950387	/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg	3	A Minecraft Movie	panosdim@gmail.com	t
51	604079	/wobVTa99eW0ht6c1rNNzLkazPtR.jpg	\N	The Long Walk	panosdim@gmail.com	\N
52	1078605	/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg	\N	Weapons	panosdim@gmail.com	\N
53	533533	/lyq8uQzxWTCIxWEKuxyQPrbVu40.jpg	\N	TRON: Ares	panosdim@gmail.com	\N
54	1062722	/2ixPMFWyKtQ9C4ROo9xA12ci2yU.jpg	\N	Frankenstein	panosdim@gmail.com	\N
55	1087891	/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg	4	The Amateur	panosdim@gmail.com	t
27	986056	/jrlCcyFJek3BWnZhpU6MHtTMoDK.jpg	4	Thunderbolts*	panosdim@gmail.com	t
56	425274	/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg	\N	Now You See Me: Now You Don't	panosdim@gmail.com	\N
\.

--
-- Data for Name: movie_providers
--

COPY public.movie_providers (movie_id, logo_path, provider_name) FROM stdin;
25	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
28	/8z7rC8uIDaTM91X0ZfkRf04ydj2.jpg	Google Play Movies
28	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
11	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
39	/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg	Netflix
38	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
31	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
40	/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg	Netflix
21	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
32	/pvske1MyAoymrs5bguRfVqYiM9a.jpg	Amazon Prime Video
41	/9ghgSC0MA082EL6HLCW3GalykFD.jpg	Apple TV
\.

--
-- Sequences
--

SELECT pg_catalog.setval('public.app_user_id_seq', (SELECT MAX(id) FROM public.app_user));
SELECT pg_catalog.setval('public.movie_id_seq', (SELECT MAX(id) FROM public.movie));

--
-- Constraints
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);

--
-- Foreign keys
--

ALTER TABLE ONLY public.movie_providers
    ADD CONSTRAINT fkluutfy9g56y6klgbt04opeoam FOREIGN KEY (movie_id) REFERENCES public.movie(id);
